### ISSUE TITLE
Comparison taken as poetic assignment

### ISSUE THREAD

**Issue by oleobal** [oleobal/rockstar-interpreter#9]
We should in theory have the facilities for the spec's `fizzbuzz.rock`, but in practice we fail on this line : 
```
If Midnight taking my world, Fire is nothing and Midnight taking my world, Hate is nothing
```

Trace : 
```
Traceback (most recent call last):
  File ".\rockstar.py", line 881, in <module>
    processProgram(f.readline(), f, context, displayAST=args.displayAST)
  File ".\rockstar.py", line 855, in processProgram
    instruction.append({"type":"block", "value":processTextBlock(line, iterator, context)})
  File ".\rockstar.py", line 806, in processTextBlock
    currentLine = tokenize(line)
  File ".\rockstar.py", line 306, in tokenize
    expr_tokens, i = parseConditionalExpression(line, i)
  File ".\rockstar.py", line 131, in parseConditionalExpression
    raiseError(line, 'Invalid boolean expression : no conditions')
  File ".\rockstar.py", line 31, in raiseError
    raise InputProgramError("Line : "+str(line)+"\nError : "+str(text))
__main__.InputProgramError: Line : If Midnight taking my world, Fire is nothing and Midnight taking my world, Hate is nothing
Error : Invalid boolean expression : no conditions
```

Let's get this sorted out and we'll be golden !

**Comment by Zebralt** [comment]
That's because the conditional expression parser is too weak. It expects the let membre to be a variable, then to find a conditional operator, then calls `tokenize` on the right member rather than trying to tokenize each side of the operator. I'll fix this soon.
